export const FETCH_ALL_ACAPS_SUCCESS = "FETCH_ALL_ACAPS_SUCCESS";
export const FETCH_ACAP_BYNAME = "FETCH_ACAP_BYNAME";
export const FETCH_DELETE_ACAP = "FETCH_DELETE_ACAP";
export const FETCH_PUT_ACAP = "FETCH_PUT_ACAP";
export const FETCH_CREATE_ACAP = "FETCH_CREATE_ACAP";
